server:
  port: 8083
  servlet:
    context-path: /api 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: child-scrapper
  data:
    rest:
      basePath: /api             